### ISSUE TITLE
Docker arguments in the UI

### ISSUE THREAD

**Issue by ashic** [HubSpot/Singularity#592] opened 2015-07-07 01:50 UTC
The UI doesn't seem to provide a way to pass arguments to docker containers. For example, the redis container: https://registry.hub.docker.com/_/redis/ can be passed some arguments

```
docker run --name some-redis -d redis redis-server --appendonly yes
```

Is something like this possible in the current UI?

**Comment by ssalinas** [comment] 2015-07-07 02:02
Right now there is not support for that in the UI. 

If posting to the api you can add arguments to the command run in the container to the command field of the task info (ie command would be `redis-server --appendonly yes`)

As for the docker run arguments, mesos does support a `parameters` field for passing arguments like that. However Singularity currently doesn't pass those fields along right now. I will leave this issue open so we can implement that functionality

**Comment by ssalinas** [comment] 2016-03-18 19:28
Docker parameters are supported on the backend, going to close this one as a dupe of #897 and track the progress updating the ui inputs there

**Closed by ssalinas** 2016-03-18 19:28 UTC
