### ISSUE TITLE
Singularity failed but no election for new master

### ISSUE THREAD

**Issue by carlf** [HubSpot/Singularity#1753] opened 2018-03-05 21:17 UTC
I ran into this today and I'm not sure the cause. Singularity halted which is not entirely surprising. More surprising is that there was never an election for a new master. Relevant log entries here. Please let me know if there's anything else you need or anything I can do to help.

```
ERROR [2018-03-05 20:45:38,946] com.hubspot.singularity.scheduler.SingularityHealthchecker: Caught throwable while re-enqueuing health check for scheduling-test-ci-teamcity_2018_01_29T19_42_47-1520282702975-1-mesos_slave1_qa_uswest2.qas
ql.opentable.com-us_west_2c, aborting
! java.lang.IllegalStateException: instance must be started before calling this method
! at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
! at org.apache.curator.framework.imps.CuratorFrameworkImpl.getChildren(CuratorFrameworkImpl.java:379)
! at com.hubspot.singularity.data.CuratorManager.getChildren(CuratorManager.java:131)
! at com.hubspot.singularity.data.TaskManager.getNumNonstartupHealthchecks(TaskManager.java:519)
! at com.hubspot.singularity.scheduler.SingularityHealthchecker.enqueueHealthcheck(SingularityHealthchecker.java:98)
! at com.hubspot.singularity.scheduler.SingularityHealthchecker.reEnqueueOrAbort(SingularityHealthchecker.java:203)
! at com.hubspot.singularity.scheduler.SingularityHealthcheckAsyncHandler.saveResult(SingularityHealthcheckAsyncHandler.java:101)
! at com.hubspot.singularity.scheduler.SingularityHealthchecker.saveFailure(SingularityHealthchecker.java:240)
! at com.hubspot.singularity.scheduler.SingularityHealthchecker.asyncHealthcheck(SingularityHealthchecker.java:300)
! at com.hubspot.singularity.scheduler.SingularityHealthchecker.access$000(SingularityHealthchecker.java:45)
! at com.hubspot.singularity.scheduler.SingularityHealthchecker$1.run(SingularityHealthchecker.java:189)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)
ERROR [2018-03-05 20:45:38,946] com.hubspot.singularity.SingularityAbort: Singularity on mesos1-qa-uswest2 is aborting due to UNRECOVERABLE_ERROR
INFO  [2018-03-05 20:45:39,090] com.hubspot.singularity.mesos.SingularityMesosScheduler: Received 6 offer(s)
ERROR [2018-03-05 20:45:39,090] com.hubspot.singularity.mesos.SingularityMesosScheduler: Scheduler threw an uncaught exception - exiting
```

**Comment by ssalinas** [comment] 2018-03-05 22:07
Do you have any more to the logs? As a reference, Singularity will abort/restart when an error is encountered with mesos or we lose connection to zookeeper for too long. This is all to avoid corrupting internal state (i.e. updating task states when we can't write them to zk or talk to mesos) and is why we recommend running Singularity with something like monit to restart. Generally these aren't a big deal.

The stack trace you posted is a bit further into the shut down process. Do you have any more to those logs a bit further up? Likely from the `SingularityMesosScheduler` class

**Comment by ssalinas** [comment] 2018-03-05 22:08
Also, when you say 'no election for new master'. Do you run multiple SingularityService instances? If so, do you mean that another service did not take over leadership/scheduling? Wondering if this is a zookeeper leader election issue in that case

**Comment by carlf** [comment] 2018-03-05 22:12
This is the first ERROR for SingularityMesosScheduler:

```
ERROR [2018-03-05 20:45:38,946] com.hubspot.singularity.SingularityAbort: Singularity on mesos1-qa-uswest2 is aborting due to UNRECOVERABLE_ERROR
INFO  [2018-03-05 20:45:39,090] com.hubspot.singularity.mesos.SingularityMesosScheduler: Received 6 offer(s)
ERROR [2018-03-05 20:45:39,090] com.hubspot.singularity.mesos.SingularityMesosScheduler: Scheduler threw an uncaught exception - exiting
! java.lang.IllegalStateException: instance must be started before calling this method
! at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
! at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkExists(CuratorFrameworkImpl.java:355)
! at com.hubspot.singularity.data.CuratorManager.checkExists(CuratorManager.java:109)
! at com.hubspot.singularity.data.CuratorManager.exists(CuratorManager.java:122)
! at com.hubspot.singularity.data.DisasterManager.isDisabled(DisasterManager.java:55)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.lambda$resourceOffers$117(SingularityMesosSchedulerImpl.java:166)
! at com.hubspot.singularity.mesos.SingularitySchedulerLock.runWithOffersLock(SingularitySchedulerLock.java:76)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.callWithOffersLock(SingularityMesosSchedulerImpl.java:377)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.resourceOffers(SingularityMesosSchedulerImpl.java:161)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl$$EnhancerByGuice$$7bc5ee06.CGLIB$resourceOffers$7(<generated>)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl$$EnhancerByGuice$$7bc5ee06$$FastClassByGuice$$4fe7e49c.invoke(<generated>)
! at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
! at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75)
! at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:26)
! at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75)
! at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl$$EnhancerByGuice$$7bc5ee06.resourceOffers(<generated>)
! at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
! at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
! at rx.internal.operators.OnSubscribeRefCount$2.onNext(OnSubscribeRefCount.java:120)
! at rx.internal.operators.OperatorPublish$PublishSubscriber.dispatch(OperatorPublish.java:588)
! at rx.internal.operators.OperatorPublish$PublishSubscriber.onNext(OperatorPublish.java:286)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:399)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:357)
! at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:852)
! at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowpath(OnSubscribeFromIterable.java:117)
! at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:89)
! at rx.Subscriber.setProducer(Subscriber.java:211)
! at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63)
! at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34)
! at rx.Observable.unsafeSubscribe(Observable.java:9861)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:250)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.observers.SerializedObserver.onNext(SerializedObserver.java:92)
! at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:94)
! at rx.internal.operators.OperatorBufferWithTime$ExactSubscriber.onCompleted(OperatorBufferWithTime.java:272)
! at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:284)
! at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:219)
! at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$1.call(EventLoopsScheduler.java:172)
! at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)
```

When I say there was no election, I mean that my expectation is that, if one singularity fails, another would take over as subscribed and connected. In this case, it stayed subscribed and connected despite being unable to schedule anything. Perhaps that is expected behavior and I just haven't bumped into it before?

**Comment by ssalinas** [comment] 2018-03-05 22:18
You are correct that another singularity should have taken over and subscribed. For reference on that `instance must be started` exception, it's an indication that curator client (for zookeeper) has already shut down, but was asked to do something. Two follow up questions:
- Was the proc still running after those stack traces? (Wondering if it never completely shut down and got stuck somewhere)
- Are there and indications on the other mesos instances of leadership changing?

**Comment by ssalinas** [comment] 2018-03-23 13:32
FYI, we found a spot in our own code where an exception was being hidden. It will be properly caught in https://github.com/HubSpot/Singularity/pull/1755. We haven't been able to reproduce since that single incident to actually find what the error being covered up actually was, but the above fix will at least throw the exception back up so things will continue processing. I'll probably cut a bugfix release next week with this and a few other things

**Comment by carlf** [comment] 2018-04-26 15:57
We just had a recurrence on 0.19.2. The error message looks identical to me. Included for completeness. No additional exceptions.

```
ERROR [2018-04-26 15:37:36,014] com.hubspot.singularity.mesos.SingularityMesosScheduler: Scheduler threw an uncaught exception - exiting
! java.lang.IllegalStateException: instance must be started before calling this method
! at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
! at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkExists(CuratorFrameworkImpl.java:355)
! at com.hubspot.singularity.data.CuratorManager.checkExists(CuratorManager.java:109)
! at com.hubspot.singularity.data.CuratorManager.exists(CuratorManager.java:122)
! at com.hubspot.singularity.data.DisasterManager.isDisabled(DisasterManager.java:55)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.lambda$resourceOffers$129(SingularityMesosSchedulerImpl.java:168)
! at com.hubspot.singularity.mesos.SingularitySchedulerLock.runWithOffersLock(SingularitySchedulerLock.java:76)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.callWithOffersLock(SingularityMesosSchedulerImpl.java:389)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl.resourceOffers(SingularityMesosSchedulerImpl.java:163)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl$$EnhancerByGuice$$7bc5ee06.CGLIB$resourceOffers$7(<generated>)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl$$EnhancerByGuice$$7bc5ee06$$FastClassByGuice$$4fe7e49c.invoke(<generated>)
! at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
! at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75)
! at com.palominolabs.metrics.guice.TimedInterceptor.invoke(TimedInterceptor.java:26)
! at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75)
! at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55)
! at com.hubspot.singularity.mesos.SingularityMesosSchedulerImpl$$EnhancerByGuice$$7bc5ee06.resourceOffers(<generated>)
! at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
! at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
! at rx.internal.operators.OnSubscribeRefCount$2.onNext(OnSubscribeRefCount.java:120)
! at rx.internal.operators.OperatorPublish$PublishSubscriber.dispatch(OperatorPublish.java:588)
! at rx.internal.operators.OperatorPublish$PublishSubscriber.onNext(OperatorPublish.java:286)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:399)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:357)
! at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:852)
! at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowpath(OnSubscribeFromIterable.java:117)
! at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:89)
! at rx.Subscriber.setProducer(Subscriber.java:211)
! at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:63)
! at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:34)
! at rx.Observable.unsafeSubscribe(Observable.java:9861)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:250)
! at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
! at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
! at rx.observers.SerializedObserver.onNext(SerializedObserver.java:92)
! at rx.observers.SerializedSubscriber.onNext(SerializedSubscriber.java:94)
! at rx.internal.operators.OperatorBufferWithTime$ExactSubscriber.emit(OperatorBufferWithTime.java:298)
! at rx.internal.operators.OperatorBufferWithTime$ExactSubscriber$1.call(OperatorBufferWithTime.java:284)
! at rx.Scheduler$Worker$1.call(Scheduler.java:136)
! at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
! at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
! at java.lang.Thread.run(Thread.java:748)
INFO  [2018-04-26 15:37:36,015] com.hubspot.singularity.mesos.SingularityMesosScheduler: Scheduler is moving to stopped, current state: SUBSCRIBED
INFO  [2018-04-26 15:37:36,015] com.hubspot.singularity.mesos.SingularityMesosScheduler: Scheduler now in state: STOPPED
ERROR [2018-04-26 15:37:36,015] com.hubspot.singularity.SingularityAbort: Singularity on mesos3-qa-sf is aborting due to UNRECOVERABLE_ERROR
```

**Comment by carlf** [comment] 2018-04-26 15:57
Note that this seems to happen with more regularity which decommissioning hosts. Not sure if that helps at all.

**Comment by ssalinas** [comment] 2018-04-30 19:29
To clarify, are you seeing the jvm hang on these, or is Singularity completely shutting down? I ask because it is by design for it to abort if there are possible zookeeper issues, as this could corrupt internal state and it is better to wait for zookeeper to be available again.

In the trace above, were there any additional exceptions above that? It would be odd for zookeeper to just shut down and there might be an additional cause above that originally caused Singularity to attempt an abort

**Comment by ssalinas** [comment] 2018-06-14 13:17
Just checked our cluster is running 3.4.5 currently. Very possible there was a regressing we hadn't upgraded to just yet. What types of exceptions are at the ends of the logs for the Singularity instance that thinks it is the leader? Is it just the instance not started stuff, or is there something preceding that as well?

**Comment by jay-chin** [comment] 2018-07-13 12:49
We have been having quite frequent crashes in our pre-prod environments running 0.20.1. What we see preceding the crash is connection errors in ZK 

```
2018-07-13 07:57:31,171 [myid:2] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@902] - Connection request from old client /10.70.8.162:38536; will be dropped if server is in r-o mode
2018-07-13 07:57:31,172 [myid:2] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@902] - Connection request from old client /10.70.6.100:56280; will be dropped if server is in r-o mode
2018-07-13 07:57:31,173 [myid:2] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@902] - Connection request from old client /10.70.6.101:54272; will be dropped if server is in r-o mode
2018-07-13 07:57:31,201 [myid:2] - ERROR [LearnerHandler-/10.70.6.121:45598:LearnerHandler@648] - Unexpected exception causing shutdown while sock still open
2018-07-13 07:57:31,201 [myid:2] - WARN  [LearnerHandler-/10.70.6.121:45598:LearnerHandler@661] - ******* GOODBYE /10.70.6.121:45598 ******
```

ZK then restarts, followed by Mesos, then Singularity.

Mesos itself recovers fine and is able to elect a new leader. However Singularity remains in a limbo state with no elected masters. There are errors in the newly started ZK showing connection issues from Singularity:

```
2018-07-13 07:58:24,093 [myid:2] - ERROR [LearnerHandler-/10.70.6.121:48870:LearnerHandler@648] - Unexpected exception causing shutdown while sock still open
java.io.EOFException
        at java.io.DataInputStream.readInt(DataInputStream.java:392)
        at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:63)
        at org.apache.zookeeper.server.quorum.QuorumPacket.deserialize(QuorumPacket.java:85)
        at org.apache.jute.BinaryInputArchive.readRecord(BinaryInputArchive.java:99)
        at org.apache.zookeeper.server.quorum.LearnerHandler.run(LearnerHandler.java:530)
2018-07-13 07:58:24,093 [myid:2] - WARN  [LearnerHandler-/10.70.6.121:48870:LearnerHandler@661] - ******* GOODBYE /10.70.6.121:48870 ******
```

Let me know if you need more details.

**Comment by ssalinas** [comment] 2018-07-13 13:02
I have not seen those exceptions before, though likely because we are on an older version of zookeeper. The `will be dropped if server is in r-o mode` I believe points to an older client against a newer zookeeper server. I've tried running Singularity locally against newer zookeper versions in docker before and it seems to stay connected fine for hours. From the Singularity side we can certainly attempt an upgrade to zookeeper client version. But, if zookeeper is crashing out I'm wondering if this is more of a zookeeper configuration issue.

**Comment by stevenschlansker** [comment] 2018-07-19 23:11
We've seen strong circumstantial evidence that says these crashes are induced by a poorly integrated deployment system.  It attempts to do many many request updates, to the point where we get north of 10k items in the request history.  Once the request history is this large, Singularity has extreme trouble reading it quickly to generate statistics / run the scheduler / etc, and it manifests in these confusing and bad ways.

While we certainly are going to have to fix our deployment application, it'd be nice if Singularity could provide some better diagnostics -- "timed out reading task `my-dumb-deployer` with 15354 children" or something like that.  The fact that the ZK protocol / usage can't handle these sorts of cases well is unfortunate..

**Comment by ssalinas** [comment] 2018-07-20 00:59
@stevenschlansker I can take a look at logs some more, but whenever we've seen zk issues internally there have been pretty descriptive messages in the logs like 'timed out waiting for ... from zookeeper'. Also, when talking about the history, are you talking request updates or task history? Internally we offload most things to mysql which saves quite a bit of load on zookeeper for all history items. I would encourage setting that up if you don't have it already

**Comment by stevenschlansker** [comment] 2018-07-20 16:55
Yeah, it usually does end up in the logs.  But it's also hard to find amongst the tons of log lines that end up coming out in such a failure.
I agree, we should set up a database to offload some of the ZK work.

**Comment by jay-chin** [comment] 2018-07-31 11:10
I'm testing MySQL on one of our clusters right now and there have not been any crashes so far. Fingers crossed.

I'm also currently testing failure scenarios in the case where MySQL becomes unreachable and if it does affect the cluster operationally. Do you have any details on how the cluster would cope when MySQL goes down ?

**Comment by ssalinas** [comment] 2018-07-31 13:00
In general things will operate as normal if mysql is not available since it is mainly used for historical data. The UI may not be fully populated however.

The only check related to new actions that relies on mysql is deploys, since it checks for a list of historical deploy ids to ensure there are no duplicates

**Comment by mikebell90** [comment] 2018-08-03 14:38
So if MySQL is down are you saying new deploys probably won’t work @ssalinas ?

**Comment by jay-chin** [comment] 2018-08-03 17:30
I've tested shutting down MySQL and singularity won't start up - I believe this is by design.

I'm also trying to get some stats to show how big an impact MySQL has on scheduling, etc. I've tried looking at the graphite app metrics that are exposed to compare 2 clusters ( 1 with MySQL and the other without). Would you have any quick pointers on which app  metrics would be a good measure for scheduling performance and identifying bottlenecks ?

Thanks once again.

**Comment by ssalinas** [comment] 2018-08-06 12:32
Scheduling shouldn't have any impact on scheduling itself. All 'live' or active task data is still stored and accessed in zookeeper. Additional task data is moved to mysql when the task has reached a terminal status.

The main bottleneck we saw in our own Singularity instance with sql was more around status update processing than offer processing. However since the PR to move to a new locking scheme (https://github.com/HubSpot/Singularity/pull/1702) released in 0.19, we have not seen an issue there either. There is an avg delay for status updates recorded in the SingularityState json to view this (https://github.com/HubSpot/Singularity/blob/master/SingularityBase/src/main/java/com/hubspot/singularity/SingularityState.java#L61)

**Comment by ssalinas** [comment] 2018-08-27 16:35
Just checking in here. Have you guys had any success with addition of sql/different zk versions/etc? I'm open to trying a client upgrade in Singularity if we think that may solve things.

**Comment by jay-chin** [comment] 2018-09-11 10:56
Thanks for checking in. We are currently testing out mysql in one of our pre-prod clusters together with a non-db cluster just for comparison. The bulk of our issues are gone now after adding additional alerting and removing requests that were creating thousands of tasks in an out of control fashion.

We have also a PR that includes Postgres support which we will soon be shortly testing in pre-prod.

**Comment by mikebell90** [comment] 2018-09-18 18:59
We discussed today @ssalinas and this issue can be closed. Thanks for your assistance!

**Closed** 2018-09-18 20:13 UTC
