### ISSUE TITLE
Requests dependencies & constraints

### ISSUE THREAD

**Issue by pgillet** [HubSpot/Singularity#1419] opened 2017-02-09 15:43 UTC
Is it possible to specify dependencies and constraints in the sense of Marathon (sorry) for requests?
E.g. A service A depends of a service B. If the service B is down, the service A should be marked down as well.

**Comment by ssalinas** [comment] 2017-02-10 16:26
Right now we do not have support for this, although related features have been request (see #1007)

**Comment by ssalinas** [comment] 2017-10-11 02:25
closing as a dupe of #1007 , there is more conversation in the other issue

**Closed by ssalinas** 2017-10-11 02:25 UTC
